import type { Category, Order, Product } from "@/lib/types";

/* ============================================================
   MOCK DATA — placeholder content for the UI prototype.
   Later this is replaced by real data from the database/admin.
   ============================================================ */

export const CATEGORIES: Category[] = [
  {
    id: "c1",
    slug: "cuisine",
    name: "Filtres de cuisine",
    nameAr: "فلاتر المطبخ",
    tagline: "Osmose inverse sous évier, 5 à 7 étapes",
    icon: "kitchen",
    hue: 205,
  },
  {
    id: "c2",
    slug: "fontaines",
    name: "Fontaines à eau",
    nameAr: "نافورات الماء",
    tagline: "Distributeurs chaud / froid pour bureau & maison",
    icon: "fountain",
    hue: 195,
  },
  {
    id: "c3",
    slug: "semi-industriel",
    name: "Semi-industriel",
    nameAr: "شبه صناعي",
    tagline: "Grand débit 400+ GPD pour cafés, restaurants, hôtels",
    icon: "industrial",
    hue: 212,
  },
  {
    id: "c4",
    slug: "filtres-rechange",
    name: "Filtres de rechange",
    nameAr: "فلاتر التبديل",
    tagline: "Cartouches & membranes pour tous nos systèmes",
    icon: "cartridge",
    hue: 188,
  },
  {
    id: "c5",
    slug: "pieces",
    name: "Pièces & accessoires",
    nameAr: "قطع الغيار",
    tagline: "Pompes, robinets, réservoirs et raccords",
    icon: "parts",
    hue: 218,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "aquabo-6-st",
    name: "AQUABO 6-ST",
    categorySlug: "cuisine",
    shortDescription:
      "Système d'osmose inverse 6 étapes — notre best-seller pour la cuisine.",
    description:
      "Le AQUABO 6-ST purifie votre eau du robinet en 6 étapes pour une eau pure, sans goût de chlore ni impuretés. Idéal pour les familles, il s'installe sous l'évier et délivre une eau minéralisée prête à boire. Membrane haute performance et réservoir de 12L.",
    price: 1900,
    oldPrice: 2300,
    rating: 4.8,
    reviewCount: 214,
    stages: 6,
    capacity: "75 GPD",
    warranty: "2 ans",
    badges: ["Best Seller"],
    inStock: true,
    stock: 38,
    bestSeller: true,
    hue: 205,
    features: [
      "Purification en 6 étapes",
      "Reminéralisation de l'eau",
      "Réservoir de 12 litres",
      "Robinet inox inclus",
      "Installation facile sous évier",
    ],
    specs: [
      { label: "Étapes", value: "6" },
      { label: "Débit", value: "75 GPD (~285 L/jour)" },
      { label: "Réservoir", value: "12 L" },
      { label: "Pression", value: "0.3 – 0.6 MPa" },
      { label: "Garantie", value: "2 ans" },
    ],
    variants: [
      { id: "v1", label: "Standard", priceDelta: 0 },
      { id: "v2", label: "+ Pompe booster", priceDelta: 350 },
    ],
    reviews: [
      {
        id: "r1",
        author: "Yassine B.",
        city: "Casablanca",
        rating: 5,
        date: "2026-05-12",
        title: "Eau excellente",
        body: "Installé en 1h, l'eau a un goût parfait. Toute la famille boit plus d'eau maintenant.",
        verified: true,
      },
      {
        id: "r2",
        author: "Fatima Z.",
        city: "Rabat",
        rating: 5,
        date: "2026-04-28",
        title: "Je recommande",
        body: "Livraison rapide et le centre d'appel m'a bien expliqué. Très satisfaite.",
        verified: true,
      },
      {
        id: "r3",
        author: "Omar K.",
        city: "Marrakech",
        rating: 4,
        date: "2026-04-03",
        title: "Bon produit",
        body: "Fonctionne très bien. J'enlève une étoile car le réservoir prend de la place.",
        verified: true,
      },
    ],
  },
  {
    id: "p2",
    slug: "ocean-6-st",
    name: "O'CÉAN 6-ST",
    categorySlug: "cuisine",
    shortDescription:
      "Osmose inverse 6 étapes au design compact et au prix doux.",
    description:
      "Le O'CÉAN 6-ST offre une purification complète en 6 étapes dans un format compact. Parfait pour les petites cuisines, il garantit une eau pure au quotidien à un prix accessible.",
    price: 1700,
    rating: 4.7,
    reviewCount: 156,
    stages: 6,
    capacity: "75 GPD",
    warranty: "2 ans",
    badges: ["Best Seller"],
    inStock: true,
    stock: 25,
    bestSeller: true,
    hue: 198,
    features: [
      "6 étapes de filtration",
      "Format compact",
      "Robinet dédié inclus",
      "Cartouches faciles à changer",
    ],
    specs: [
      { label: "Étapes", value: "6" },
      { label: "Débit", value: "75 GPD" },
      { label: "Réservoir", value: "10 L" },
      { label: "Garantie", value: "2 ans" },
    ],
    reviews: [
      {
        id: "r4",
        author: "Hicham A.",
        city: "Fès",
        rating: 5,
        date: "2026-05-01",
        title: "Rapport qualité/prix top",
        body: "Compact et efficace. Parfait pour mon appartement.",
        verified: true,
      },
    ],
  },
  {
    id: "p3",
    slug: "glasse-plus-7-st",
    name: "Glasse Plus 7-ST",
    categorySlug: "cuisine",
    shortDescription:
      "7 étapes avec minéralisation alcaline pour une eau encore plus saine.",
    description:
      "Le Glasse Plus ajoute une 7ème étape de minéralisation alcaline qui rééquilibre le pH de l'eau et y ajoute des minéraux essentiels. Pour ceux qui veulent le meilleur pour leur santé.",
    price: 1700,
    oldPrice: 1950,
    rating: 4.9,
    reviewCount: 98,
    stages: 7,
    capacity: "75 GPD",
    warranty: "2 ans",
    badges: ["Promo"],
    inStock: true,
    stock: 19,
    hue: 210,
    features: [
      "7 étapes dont minéralisation alcaline",
      "Équilibre le pH de l'eau",
      "Ajoute des minéraux essentiels",
      "Réservoir 12 L",
    ],
    specs: [
      { label: "Étapes", value: "7" },
      { label: "Débit", value: "75 GPD" },
      { label: "pH", value: "Alcalin 7.5 – 9" },
      { label: "Garantie", value: "2 ans" },
    ],
    reviews: [
      {
        id: "r5",
        author: "Salma R.",
        city: "Tanger",
        rating: 5,
        date: "2026-05-09",
        title: "Eau alcaline parfaite",
        body: "On sent la différence de goût. Très contente de mon achat.",
        verified: true,
      },
    ],
  },
  {
    id: "p4",
    slug: "eco-agua-premium",
    name: "ECO-AGUA Premium",
    categorySlug: "cuisine",
    shortDescription:
      "Système 5 étapes économique, idéal pour débuter.",
    description:
      "L'ECO-AGUA Premium est notre solution d'entrée de gamme : 5 étapes de purification fiables à petit prix. Une excellente première installation pour une eau saine sans se ruiner.",
    price: 1020,
    oldPrice: 1200,
    rating: 4.5,
    reviewCount: 132,
    stages: 5,
    capacity: "50 GPD",
    warranty: "1 an",
    badges: ["Promo"],
    inStock: true,
    stock: 44,
    hue: 192,
    features: [
      "5 étapes de filtration",
      "Prix économique",
      "Compact et discret",
      "Robinet inclus",
    ],
    specs: [
      { label: "Étapes", value: "5" },
      { label: "Débit", value: "50 GPD" },
      { label: "Réservoir", value: "8 L" },
      { label: "Garantie", value: "1 an" },
    ],
    reviews: [
      {
        id: "r6",
        author: "Karim L.",
        city: "Agadir",
        rating: 4,
        date: "2026-03-22",
        title: "Bon pour commencer",
        body: "Fait le travail, bon prix. Je le recommande pour un premier filtre.",
        verified: true,
      },
    ],
  },
  {
    id: "p5",
    slug: "puro-7-st-smart",
    name: "PURO 7-ST Smart",
    categorySlug: "cuisine",
    shortDescription:
      "7 étapes avec écran intelligent qui affiche la qualité de l'eau (TDS).",
    description:
      "Le PURO 7-ST Smart intègre un écran digital qui affiche en temps réel la qualité de votre eau (TDS) et vous alerte quand changer les filtres. Le summum de la technologie de purification domestique.",
    price: 2200,
    rating: 4.9,
    reviewCount: 41,
    stages: 7,
    capacity: "100 GPD",
    warranty: "2 ans",
    badges: ["Nouveau"],
    inStock: true,
    stock: 12,
    hue: 215,
    features: [
      "Écran digital TDS en temps réel",
      "Alerte de changement de filtre",
      "Débit rapide 100 GPD",
      "7 étapes + minéralisation",
    ],
    specs: [
      { label: "Étapes", value: "7" },
      { label: "Débit", value: "100 GPD" },
      { label: "Écran", value: "Digital TDS" },
      { label: "Garantie", value: "2 ans" },
    ],
    reviews: [
      {
        id: "r7",
        author: "Nadia E.",
        city: "Casablanca",
        rating: 5,
        date: "2026-05-20",
        title: "Technologie au top",
        body: "L'écran qui montre la qualité de l'eau est génial. On voit la différence.",
        verified: true,
      },
    ],
  },
  {
    id: "p6",
    slug: "fontaine-office-pro",
    name: "Fontaine Office Pro",
    categorySlug: "fontaines",
    shortDescription:
      "Distributeur eau chaude & froide avec filtration intégrée pour le bureau.",
    description:
      "La Fontaine Office Pro distribue de l'eau chaude et froide filtrée à la demande. Branchée directement sur l'arrivée d'eau, plus besoin de bonbonnes. Parfaite pour les bureaux et salles d'attente.",
    price: 2600,
    rating: 4.6,
    reviewCount: 67,
    capacity: "Chaud / Froid",
    warranty: "2 ans",
    badges: [],
    inStock: true,
    stock: 15,
    hue: 196,
    features: [
      "Eau chaude et froide",
      "Filtration intégrée",
      "Sans bonbonne (raccordement direct)",
      "Design inox pour le bureau",
    ],
    specs: [
      { label: "Eau chaude", value: "90 °C" },
      { label: "Eau froide", value: "5 °C" },
      { label: "Filtration", value: "4 étapes" },
      { label: "Garantie", value: "2 ans" },
    ],
    reviews: [],
  },
  {
    id: "p7",
    slug: "fontaine-compact-home",
    name: "Fontaine Compact Home",
    categorySlug: "fontaines",
    shortDescription:
      "Petite fontaine de comptoir, eau fraîche filtrée à la maison.",
    description:
      "La Fontaine Compact Home se pose sur le comptoir et offre une eau fraîche filtrée à tout moment. Idéale pour les familles qui veulent une eau pure sans installation sous évier.",
    price: 1450,
    rating: 4.4,
    reviewCount: 38,
    capacity: "Froid",
    warranty: "1 an",
    badges: [],
    inStock: true,
    stock: 22,
    hue: 190,
    features: [
      "Format comptoir compact",
      "Eau fraîche filtrée",
      "Facile à remplir",
      "Silencieuse",
    ],
    specs: [
      { label: "Capacité", value: "5 L" },
      { label: "Filtration", value: "3 étapes" },
      { label: "Garantie", value: "1 an" },
    ],
    reviews: [],
  },
  {
    id: "p8",
    slug: "aquaflow-400-gpd",
    name: "AquaFlow 400 GPD",
    categorySlug: "semi-industriel",
    shortDescription:
      "Système grand débit 400 GPD pour cafés, restaurants et snacks.",
    description:
      "L'AquaFlow 400 GPD est conçu pour les professionnels : cafés, restaurants et snacks. Avec 400 gallons par jour, il fournit une eau pure en grande quantité pour la boisson, le café et la cuisine.",
    price: 6900,
    oldPrice: 7800,
    rating: 4.8,
    reviewCount: 29,
    stages: 6,
    capacity: "400 GPD",
    warranty: "2 ans",
    badges: ["Best Seller", "Promo"],
    inStock: true,
    stock: 8,
    bestSeller: true,
    hue: 212,
    features: [
      "Grand débit 400 GPD",
      "Pour usage professionnel",
      "Pompe booster incluse",
      "Réservoir 75 L",
    ],
    specs: [
      { label: "Débit", value: "400 GPD (~1 500 L/jour)" },
      { label: "Étapes", value: "6" },
      { label: "Réservoir", value: "75 L" },
      { label: "Garantie", value: "2 ans" },
    ],
    reviews: [
      {
        id: "r8",
        author: "Café Atlas",
        city: "Marrakech",
        rating: 5,
        date: "2026-04-15",
        title: "Parfait pour notre café",
        body: "Débit largement suffisant pour le service. Installation pro et rapide.",
        verified: true,
      },
    ],
  },
  {
    id: "p9",
    slug: "aquaflow-800-gpd-resto",
    name: "AquaFlow 800 GPD Resto",
    categorySlug: "semi-industriel",
    shortDescription:
      "Très grand débit 800 GPD pour hôtels et restaurants à fort volume.",
    description:
      "L'AquaFlow 800 GPD Resto est notre système le plus puissant, pensé pour les hôtels et grands restaurants. Double membrane et réservoir 150 L pour ne jamais manquer d'eau pure.",
    price: 12900,
    rating: 4.9,
    reviewCount: 11,
    stages: 6,
    capacity: "800 GPD",
    warranty: "3 ans",
    badges: [],
    inStock: true,
    stock: 4,
    hue: 218,
    features: [
      "Très grand débit 800 GPD",
      "Double membrane",
      "Réservoir 150 L",
      "Maintenance professionnelle disponible",
    ],
    specs: [
      { label: "Débit", value: "800 GPD (~3 000 L/jour)" },
      { label: "Membranes", value: "2" },
      { label: "Réservoir", value: "150 L" },
      { label: "Garantie", value: "3 ans" },
    ],
    reviews: [],
  },
  {
    id: "p10",
    slug: "kit-5-filtres-rechange",
    name: "Kit 5 filtres de rechange",
    categorySlug: "filtres-rechange",
    shortDescription:
      "Jeu complet de 5 cartouches pour entretenir votre système d'osmose.",
    description:
      "Gardez votre eau pure toute l'année avec ce kit de 5 cartouches de rechange compatibles avec la plupart de nos systèmes 5 à 7 étapes. À changer tous les 6 à 12 mois.",
    price: 320,
    oldPrice: 400,
    rating: 4.7,
    reviewCount: 187,
    warranty: "—",
    badges: ["Promo"],
    inStock: true,
    stock: 120,
    hue: 188,
    features: [
      "5 cartouches incluses",
      "Compatible systèmes 5–7 étapes",
      "À changer tous les 6–12 mois",
      "Maintient la qualité de l'eau",
    ],
    specs: [
      { label: "Contenu", value: "5 cartouches" },
      { label: "Compatibilité", value: "Systèmes 5–7 étapes" },
      { label: "Durée", value: "6–12 mois" },
    ],
    reviews: [
      {
        id: "r9",
        author: "Rachid M.",
        city: "Meknès",
        rating: 5,
        date: "2026-05-05",
        title: "Indispensable",
        body: "Je commande ce kit chaque année. Facile à changer, eau toujours parfaite.",
        verified: true,
      },
    ],
  },
  {
    id: "p11",
    slug: "membrane-ro-100-gpd",
    name: "Membrane RO 100 GPD",
    categorySlug: "filtres-rechange",
    shortDescription:
      "Membrane d'osmose inverse haute performance 100 GPD.",
    description:
      "Membrane d'osmose inverse de remplacement 100 GPD, le cœur de votre système de purification. Élimine jusqu'à 99% des contaminants dissous.",
    price: 290,
    rating: 4.8,
    reviewCount: 76,
    capacity: "100 GPD",
    warranty: "—",
    badges: [],
    inStock: true,
    stock: 64,
    hue: 186,
    features: [
      "Débit 100 GPD",
      "Élimine 99% des contaminants",
      "Longue durée de vie (2–3 ans)",
      "Compatible standard",
    ],
    specs: [
      { label: "Débit", value: "100 GPD" },
      { label: "Rejet", value: "99% TDS" },
      { label: "Durée", value: "2–3 ans" },
    ],
    reviews: [],
  },
  {
    id: "p12",
    slug: "pompe-booster",
    name: "Pompe booster de pression",
    categorySlug: "pieces",
    shortDescription:
      "Augmente la pression pour un meilleur débit de votre système.",
    description:
      "Pompe booster qui augmente la pression d'eau entrante pour améliorer le débit et l'efficacité de votre système d'osmose inverse, surtout en cas de faible pression.",
    price: 350,
    rating: 4.6,
    reviewCount: 54,
    warranty: "1 an",
    badges: [],
    inStock: true,
    stock: 33,
    hue: 220,
    features: [
      "Augmente la pression d'eau",
      "Améliore le débit",
      "Installation simple",
      "Silencieuse",
    ],
    specs: [
      { label: "Tension", value: "24V DC" },
      { label: "Usage", value: "Faible pression d'eau" },
      { label: "Garantie", value: "1 an" },
    ],
    reviews: [],
  },
  {
    id: "p13",
    slug: "robinet-inox-premium",
    name: "Robinet inox premium",
    categorySlug: "pieces",
    shortDescription:
      "Robinet dédié élégant en inox pour eau purifiée.",
    description:
      "Robinet en inox brossé au design moderne, dédié à votre eau purifiée. Se monte sur l'évier et résiste à la corrosion pour des années d'utilisation.",
    price: 180,
    rating: 4.7,
    reviewCount: 41,
    warranty: "1 an",
    badges: [],
    inStock: true,
    stock: 58,
    hue: 224,
    features: [
      "Inox brossé premium",
      "Design moderne",
      "Anti-corrosion",
      "Montage facile",
    ],
    specs: [
      { label: "Matériau", value: "Inox 304" },
      { label: "Finition", value: "Brossé" },
      { label: "Garantie", value: "1 an" },
    ],
    reviews: [],
  },
];

/** Major Moroccan cities for the checkout dropdown. */
export const MOROCCAN_CITIES: string[] = [
  "Casablanca",
  "Rabat",
  "Marrakech",
  "Fès",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
  "Salé",
  "Mohammedia",
  "El Jadida",
  "Béni Mellal",
  "Nador",
  "Khouribga",
  "Settat",
  "Safi",
  "Larache",
  "Khémisset",
  "Berrechid",
  "Taza",
  "Essaouira",
  "Ouarzazate",
];

/** Sample orders for the admin prototype. */
export const ORDERS: Order[] = [
  {
    id: "FM-2041",
    customerName: "Yassine Bennani",
    phone: "0634585463",
    city: "Casablanca",
    address: "12 Rue des Fleurs, Maârif",
    note: "Appeler après 18h",
    items: [{ name: "AQUABO 6-ST", qty: 1, price: 1900, variantLabel: "Standard" }],
    total: 1900,
    status: "pending",
    createdAt: "2026-06-02T09:14:00",
  },
  {
    id: "FM-2040",
    customerName: "Fatima Zahra El Amrani",
    phone: "0760629315",
    city: "Rabat",
    address: "45 Avenue Hassan II, Agdal",
    items: [
      { name: "Glasse Plus 7-ST", qty: 1, price: 1700 },
      { name: "Kit 5 filtres de rechange", qty: 1, price: 320 },
    ],
    total: 2020,
    status: "confirmed",
    createdAt: "2026-06-02T08:02:00",
    confirmationNote: "Confirmé par téléphone, livraison demain.",
  },
  {
    id: "FM-2039",
    customerName: "Omar Kabbaj",
    phone: "0612345678",
    city: "Marrakech",
    address: "Résidence Al Massira, Imm B, Apt 7",
    items: [{ name: "AquaFlow 400 GPD", qty: 1, price: 6900 }],
    total: 6900,
    status: "shipped",
    createdAt: "2026-06-01T15:40:00",
    confirmationNote: "Client professionnel (café).",
  },
  {
    id: "FM-2038",
    customerName: "Salma Riad",
    phone: "0655112233",
    city: "Tanger",
    address: "8 Rue de la Liberté, Centre-ville",
    items: [{ name: "O'CÉAN 6-ST", qty: 1, price: 1700 }],
    total: 1700,
    status: "delivered",
    createdAt: "2026-05-30T11:20:00",
    confirmationNote: "Livré et payé en espèces.",
  },
  {
    id: "FM-2037",
    customerName: "Karim Lahlou",
    phone: "0699887766",
    city: "Agadir",
    address: "Quartier Founty, Bloc D",
    items: [{ name: "ECO-AGUA Premium", qty: 1, price: 1020 }],
    total: 1020,
    status: "delivered",
    createdAt: "2026-05-29T16:05:00",
  },
  {
    id: "FM-2036",
    customerName: "Nadia El Fassi",
    phone: "0644556677",
    city: "Fès",
    address: "Lotissement Narjis, Rue 14",
    items: [{ name: "PURO 7-ST Smart", qty: 1, price: 2200 }],
    total: 2200,
    status: "pending",
    createdAt: "2026-06-02T07:30:00",
  },
  {
    id: "FM-2035",
    customerName: "Rachid Mansouri",
    phone: "0633221100",
    city: "Meknès",
    address: "Avenue des FAR, Imm 22",
    items: [{ name: "Kit 5 filtres de rechange", qty: 2, price: 320 }],
    total: 640,
    status: "cancelled",
    createdAt: "2026-05-28T10:00:00",
    confirmationNote: "Injoignable après 3 appels.",
  },
  {
    id: "FM-2034",
    customerName: "Hôtel Le Palmier",
    phone: "0522445566",
    city: "Casablanca",
    address: "Boulevard de la Corniche, Aïn Diab",
    note: "Facture au nom de l'hôtel",
    items: [{ name: "AquaFlow 800 GPD Resto", qty: 1, price: 12900 }],
    total: 12900,
    status: "confirmed",
    createdAt: "2026-06-01T13:12:00",
    confirmationNote: "Devis validé, installation programmée.",
  },
];

/* -------- Lookup helpers -------- */

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getProductsByCategory(slug: string): Product[] {
  return PRODUCTS.filter((p) => p.categorySlug === slug);
}

export function getBestSellers(): Product[] {
  return PRODUCTS.filter((p) => p.bestSeller);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.categorySlug === product.categorySlug && p.id !== product.id,
  ).slice(0, limit);
}
